### ISSUE TITLE
Create bin/fetch-books script

### ISSUE THREAD

**Issue by irnc** [grodno-city/alis-web-index#10]
It should fetch all books and store it to Elasticsearch. Books should be fetched by year descending (2017, 2016, ...).

- [ ] add `bin/fetch-books` which reads `.fetch-books-snapshot` and starts fetching from year from snapshot
- [ ] `bin/fetch-books` should update snapshot file after each year

**Comment by HannaKazello** [comment]
Not all records have year of publication. So, we decided that we need to fetch books by ids. 
bin/fetch-books reads .fetch-books-snapshot and starts fetching from id from snaphot and update it. If snapshot does not exist, script should starts from 0 id.
Snapshot have last id and count of records.

**Comment by HannaKazello** [comment]
closed by #12
